// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBk_UpwWPCYeZi6Aty3l09lm9QB1SnWe4',
    appId: '1:424400130055:web:04a2ee68a607bfc7859aa2',
    messagingSenderId: '424400130055',
    projectId: 'presensi-system',
    authDomain: 'presensi-system.firebaseapp.com',
    storageBucket: 'presensi-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ088GdjKx3xUxGouo6zE3nhgHm43mAhA',
    appId: '1:424400130055:android:d9afaafd9da6c629859aa2',
    messagingSenderId: '424400130055',
    projectId: 'presensi-system',
    storageBucket: 'presensi-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwz04psSYTQUCNftGv5ww6kSSXJIlw-KM',
    appId: '1:424400130055:ios:eafd219e29518133859aa2',
    messagingSenderId: '424400130055',
    projectId: 'presensi-system',
    storageBucket: 'presensi-system.firebasestorage.app',
    iosBundleId: 'com.kampus.presensi.presensiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwz04psSYTQUCNftGv5ww6kSSXJIlw-KM',
    appId: '1:424400130055:ios:eafd219e29518133859aa2',
    messagingSenderId: '424400130055',
    projectId: 'presensi-system',
    storageBucket: 'presensi-system.firebasestorage.app',
    iosBundleId: 'com.kampus.presensi.presensiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBk_UpwWPCYeZi6Aty3l09lm9QB1SnWe4',
    appId: '1:424400130055:web:a5df6416951d9615859aa2',
    messagingSenderId: '424400130055',
    projectId: 'presensi-system',
    authDomain: 'presensi-system.firebaseapp.com',
    storageBucket: 'presensi-system.firebasestorage.app',
  );
}
